name: "PROD tag push"
on:
  push:
    branches:
      - main
jobs:
  release:
    name: "project release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: commit push
        run: |
          git config --local user.email "trustyoo86@mgail.com"
          git config --local user.name "Hanseung Yoo"
          git tag ${{github.head_ref}}

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: main
